// #Stratagems
const stratagems = {
  "Machine Gun": true,
  "Anti-Material Rifle": true,
  "Stalwart": true,
  "Expendable Anti-Tank": true,
  "Recoilless Rifle": true,
  "Flamethrower": true,
  "Autocannon": true,
  "Heavy Machine Gun": true,
  "Airburst Rocket Launcher": true,
  "Railgun": true,
  "Spear": true,
  "StA-X3 W.A.S.P. Launcher": true,
  "Orbital Gatling Barrage": true,
  "Orbital Airburst Strike": true,
  "Orbital 120MM HE Barrage": true,
  "Orbital 380MM HE Barrage": true,
  "Orbital Walking Barrage": true,
  "Orbital Laser": true,
  "Orbital Railcannon Strike": true,
  "Eagle Strafing Run": true,
  "Eagle Airstrike": true,
  "Eagle Cluster Bomb": true,
  "Eagle Napalam Aistrike": true,
  "Jump Pack": true,
  "Eagle Smoke Strike": true,
  "Eagle 110MM Rocket Pods": true,
  "Eagle 500KG Bomb": true,
  "M-102 Fast Recon Vehicle": true,
  "Orbital Precision Strike": true,
  "Orbital Gas Strike": true,
  "Orbital EMS Strike": true,
  "Orbital Smoke Strike": true,
  "HMG Emplacement": true,
  "Shield Generator Relay": true,
  "Tesla Tower": true,
  "Anti-Personnel Minefield": true,
  "Supply Pack": true,
  "Grenade Launcher": true,
  "Laser Cannon": true,
  "Incendiary Mines": true,
  '"Guard Dog" Rover': true,
  "Ballistic Shield Backpack": true,
  "Arc Thrower": true,
  "Quasar Cannon": true,
  "Shield Generator Pack": true,
  "Machine Gun Sentry": true,
  "Gatling Sentry": true,
  "Mortar Sentry": true,
  '"Guard Dog"': true,
  "Autocannon Sentry": true,
  "Rocket Sentry": true,
  "EMS Mortar Sentry": true,
  "Patriot Exosuit": true,
  "Emancipator Exosuit": true,
  "MLS-4X Commando": true,
  "Anti-Tank Mines": true,
  "Orbital Napalm Barrage": true,
  "Sterilizer": true,
  '"Guard Dog" Dog Breath': true,
  "SH-51 Directional Shield": true,
  "E/AT-12 Anti-Tank Emplacement": true,
  "A/FLAM-40 Flame Sentry": true,
};

// #Primaries
const primaries = {
  "AR-23 Liberator": true,
  "AR-23P Liberator Penetrator": true,
  "AR-23C Liberator Concussive": true,
  "StA-52 Assault Rifle": true,
  "AR-23A Liberator Carbine": true,
  "AR-61 Tenderizer": true,
  "BR-14 Adjudicator": true,
  "R-2124 Constitution": true,
  "R-63 Diligence": true,
  "R-63CS Diligence Counter Sniper": true,
  "PLAS-39 Accelerator Rifle": true,
  "MP-98 Knight": true,
  "StA-11 SMG": true,
  "SMG-32 Reprimand": true,
  "SMG-37 Defender": true,
  "SMG-72 Pummeler": true,
  "SG-8 Punisher": true,
  "SG-8S Slugger": true,
  "SG-20 Halt": true,
  "SG-451 Cookout": true,
  "SG-225 Breaker": true,
  "SG-225SP Breaker Spray&Pray": true,
  "SG-225IE Breaker Incendiary": true,
  "CB-9 Exploding Crossbow": true,
  "R-36 Eruptor": true,
  "SG-8P Punisher Plasma": true,
  "ARC-12 Blitzer": true,
  "LAS-5 Scythe": true,
  "LAS-16 Sickle": true,
  "PLAS-1 Scorcher": true,
  "PLAS-101 Purifier": true,
  "Flam-66 Torcher": true,
  "JAR-5 Dominator": true,
};

// #Secondaries
const secondaries = {
  "P-2 Peacemaker": true,
  "P-19 Redeemer": true,
  "P-113 Verdict": true,
  "P-4 Senator": true,
  "CQC-19 Stun Lance": true,
  "CQC-30 Stun Baton": true,
  "P-11 Stim Pistol": true,
  "SG-22 Bushwhacker": true,
  "P-72 Crisper": true,
  "GP-31 Grenade Pistol": true,
  "LAS-7 Dagger": true,
  "Plas-15 Loyalist": true,
};

// #Grenades
const grenades = {
  "G-6 Frag": true,
  "G-12 High Explosive": true,
  "G-10 Incendiary": true,
  "G-16 Impact": true,
  "G-13 Incendiary Impact": true,
  "G-23 Stun": true,
  "G-4 Gas": true,
  "G-3 Smoke": true,
  "G-123 Thermite Grenade": true,
  "K-2 Throwing Knife": true,
};

const armor = {
  "AC-1 Dutiful": true,
  "AC-2 Obedient": true,
  "AF-02 Haz-Master": true,
  "AF-50 Noxious Ranger": true,
  "AF-52 Lockdown": true,
  "AF-91 Field Chemist": true,
  "B-01 Tactical": true,
  "B-08 Light Gunner": true,
  "B-24 Enforcer": true,
  "B-27 Fortified Commando": true,
  "CE-07 Demolition Specialist": true,
  "CE-101 Guerilla Gorilla": true,
  "CE-27 Ground Breaker": true,
  "CE-35 Trench Engineer": true,
  "CE-64 Grenadier": true,
  "CE-67 Titan": true,
  "CE-74 Breaker": true,
  "CE-81 Juggernaut": true,
  "CM-09 Bonesnapper": true,
  "CM-10 Clinician": true,
  "CM-14 Physician": true,
  "CM-17 Butcher": true,
  "CM-21 Trench Paramedic": true,
  "CW-22 Kodiak": true,
  "CW-36 Winter Warrior": true,
  "CW-4 Arctic Ranger": true,
  "CW-9 White Wolf": true,
  "DP-00 Tactical": true,
  "DP-11 Champion of the People": true,
  "DP-40 Hero of the Federation": true,
  "DP-53 Savior of the Free": true,
  "EX-00 Prototype X": true,
  "EX-03 Prototype 3": true,
  "EX-16 Prototype 16": true,
  "FS-05 Marksman": true,
  "FS-11 Executioner": true,
  "FS-23 Battle Master": true,
  "FS-34 Exterminator": true,
  "FS-37 Ravager": true,
  "FS-38 Eradicator": true,
  "FS-55 Devastator": true,
  "FS-61 Dreadnought": true,
  "I-09 Heatseeker": true,
  "I-102 Draconaught": true,
  "I-44 Salamander": true,
  "I-92 Fire Fighter": true,
  "PH-202 Twigsnapper": true,
  "PH-56 Jaguar": true,
  "PH-9 Predator": true,
  "SA-04 Combat Technician": true,
  "SA-12 Servo Assisted": true,
  "SA-25 Steel Trooper": true,
  "SA-32 Dynamo": true,
  "SC-15 Drone Master": true,
  "SC-30 Trailblazer Scout": true,
  "SC-34 Infiltrator": true,
  "SC-37 Legionnaire": true,
  "SR-18 Roadblock": true,
  "SR-24 Street Scout": true,
  "SR-64 Cinderblock": true,
  "TR-117 Alpha Commander": true,
  "TR-40 Gold Eagle": true,
  "TR-62 Knight": true,
  "TR-7 Ambassador of the Brand": true,
  "TR-9 Cavalier of Democracy": true,
  "UF-16 Inspector": true,
  "UF-50 Bloodhound": true,
  "UF-84 Doubt Killer": true,
}

// #Armor/Helmets
const armor_sets = [
  {
    helmet: "B-01 Tactical 1",
    armor: "B-01 Tactical 1",
    cape: "Drape of Glory",
    banner: "Drape of Glory",
  },
  {
    helmet: "B-01 Tactical 2",
    armor: "B-01 Tactical 2",
    cape: "Drape of Glory",
    banner: "Drape of Glory",
  },
  {
    helmet: "B-01 Tactical 3",
    armor: "B-01 Tactical 3",
    cape: "Drape of Glory",
    banner: "Drape of Glory",
  },
  {
    helmet: "B-01 Tactical 4",
    armor: "B-01 Tactical 4",
    cape: "Drape of Glory",
    banner: "Drape of Glory",
  },
  {
    helmet: "B-08 Light Gunner",
    armor: "B-08 Light Gunner",
    cape: "Foesmasher",
    banner: "Foesmasher",
  },
  {
    helmet: "SC-34 Infiltrator",
    armor: "SC-34 Infiltrator",
    cape: "Independence Bringer",
    banner: "Independence Bringer",
  },
  {
    helmet: "FS-05 Marksman",
    armor: "FS-05 Marksman",
    cape: "Liberty's Herald",
    banner: "Liberty's Herald",
  },
  {
    helmet: "FS-11 Executioner",
    armor: "FS-11 Executioner",
    cape: "Foesmasher",
    banner: "Foesmasher",
  },
  {
    helmet: "CE-35 Trench Engineer",
    armor: "CE-35 Trench Engineer",
    cape: "Tideturner",
    banner: "Tideturner",
  },
  {
    helmet: "CM-09 Bonesnapper",
    armor: "CM-09 Bonesnapper",
    cape: "Stars and Suffrage",
    banner: "Stars and Suffrage",
  },
  {
    helmet: "DP-40 Hero of the Federation",
    armor: "DP-40 Hero of the Federation",
    cape: "Unblemished Allegiance",
    banner: "Unblemished Allegiance",
  },
  {
    helmet: "FS-23 Battle Master",
    armor: "FS-23 Battle Master",
    cape: "Judgment Day",
    banner: "Judgment Day",
  },
  {
    helmet: "FS-61 Dreadnought",
    armor: "FS-61 Dreadnought",
    cape: "Liberty's Herald",
    banner: "Liberty's Herald",
  },
  {
    helmet: "SC-30 Trailblazer Scout",
    armor: "SC-30 Trailblazer Scout",
    cape: "Cresting Honor",
    banner: "Cresting Honor",
  },
  {
    helmet: "SA-04 Combat Technician",
    armor: "SA-04 Combat Technician",
    cape: "Mantle of True Citizenship",
    banner: "Mantle of True Citizenship",
  },
  {
    helmet: "CM-14 Physician",
    armor: "CM-14 Physician",
    cape: "Blazing Samaritan",
    banner: "Blazing Samaritan",
  },
  {
    helmet: "DP-11 Champion of the People",
    armor: "DP-11 Champion of the People",
    cape: "Light of Eternal Liberty",
    banner: "Light of Eternal Liberty",
  },
  {
    helmet: "SA-25 Steel Trooper",
    armor: "SA-25 Steel Trooper",
    cape: "Tyrant Hunter",
    banner: "Tyrant Hunter",
  },
  {
    helmet: "SA-12 Servo-Assisted",
    armor: "SA-12 Servo-Assisted",
    cape: "Posterity's Gratitude",
    banner: "Posterity's Gratitude",
  },
  {
    helmet: "SA-32 Dynamo",
    armor: "SA-32 Dynamo",
    cape: "Bastion of Integrity",
    banner: "Bastion of Integrity",
  },
  {
    helmet: "EX-03 Prototype 3",
    armor: "EX-03 Prototype 3",
    cape: "Botslayer",
    banner: "Botslayer",
  },
  {
    helmet: "EX-16 Prototype 16",
    armor: "EX-16 Prototype 16",
    cape: "Martyris Rex",
    banner: "Martyris Rex",
  },
  {
    helmet: "EX-00 Prototype X",
    armor: "EX-00 Prototype X",
    cape: "Agent of Oblivion",
    banner: "Agent of Oblivion",
  },
  {
    helmet: "CE-27 Ground Breaker",
    armor: "CE-27 Ground Breaker",
    cape: "Harbinger of True Quality",
    banner: "Harbinger of True Quality",
  },
  {
    helmet: "CE-07 Demolition Specialist",
    armor: "CE-07 Demolition Specialist",
    cape: "Eagle's Fury",
    banner: "Eagle's Fury",
  },
  {
    helmet: "FS-55 Devastator",
    armor: "FS-55 Devastator",
    cape: "Freedom's Tapestry",
    banner: "Freedom's Tapestry",
  },
  {
    helmet: "CW-36 Winter Warrior",
    armor: "CW-36 Winter Warrior",
    cape: "Dissident's Nightmare",
    banner: "Dissident's Nightmare",
  },
  {
    helmet: "CW-22 Kodiak",
    armor: "CW-22 Kodiak",
    cape: "Pinions of Everlasting Glory",
    banner: "Pinions of Everlasting Glory",
  },
  {
    helmet: "CW-4 Arctic Ranger",
    armor: "CW-4 Arctic Ranger",
    cape: "Order of the Venerated Ballot",
    banner: "Order of the Venerated Ballot",
  },
  {
    helmet: "B-27 Fortified Commando",
    armor: "B-27 Fortified Commando",
    cape: null,
    banner: null,
  },
  {
    helmet: "PH-9 Predator",
    armor: "PH-9 Predator",
    cape: "Mark of the Crimson Fang",
    banner: "Mark of the Crimson Fang",
  },
  {
    helmet: "PH-202 Twigsnapper",
    armor: "PH-202 Twigsnapper",
    cape: "Executioner's Canopy",
    banner: "Executioner's Canopy",
  },
  {
    helmet: "TR-40 Gold Eagle",
    armor: "TR-40 Gold Eagle",
    cape: "Foesmasher",
    banner: "Foesmasher",
  },
  {
    helmet: "I-09 Heatseeker",
    armor: "I-09 Heatseeker",
    cape: "Purifying Eclipse",
    banner: "Purifying Eclipse",
  },
  {
    helmet: "I-102 Draconaught",
    armor: "I-102 Draconaught",
    cape: "The Breach",
    banner: "The Breach",
  },
  {
    helmet: "CE-101 Guerilla Gorilla",
    armor: "CE-101 Guerilla Gorilla",
    cape: null,
    banner: null,
  },
  {
    helmet: "SC-37 Legionnaire",
    armor: "SC-37 Legionnaire",
    cape: null,
    banner: null,
  },
  {
    helmet: "AF-50 Noxious Ranger",
    armor: "AF-50 Noxious Ranger",
    cape: "Standard of Safe Distance",
    banner: "Standard of Safe Distance",
  },
  {
    helmet: "AF-02 Haz-Master",
    armor: "AF-02 Haz-Master",
    cape: "Patient Zero's Rememberance",
    banner: "Patient Zero's Rememberance",
  },
  {
    helmet: "DP-00 Tactical",
    armor: "DP-00 Tactical",
    cape: null,
    banner: null,
  },
  {
    helmet: "UF-50 Bloodhound",
    armor: "UF-50 Bloodhound",
    cape: "Pride of the Whistleblower",
    banner: "Pride of the Whistleblower",
  },
  {
    helmet: "UF-16 Inspector",
    armor: "UF-16 Inspector",
    cape: "Proof of Faultless Virtue",
    banner: "Proof of Faultless Virtue",
  },
  {
    helmet: "PH-56 Jaguar",
    armor: "PH-56 Jaguar",
    cape: null,
    banner: null,
  },
];

const data = { stratagems, primaries, secondaries, grenades, armor, armor_sets };
export default data;
