// #Stratagems
const stratagems = [
  "Machine Gun",
  "Anti-Material Rifle",
  "Stalwart",
  "Expendable Anti-Tank",
  "Recoilless Rifle",
  "Flamethrower",
  "Autocannon",
  "Heavy Machine Gun",
  "Airburst Rocket Launcher",
  "Railgun",
  "Spear",
  "StA-X3 W.A.S.P. Launcher",
  "Orbital Gatling Barrage",
  "Orbital Airburst Strike",
  "Orbital 120MM HE Barrage",
  "Orbital 380MM HE Barrage",
  "Orbital Walking Barrage",
  "Orbital Laser",
  "Orbital Railcannon Strike",
  "Eagle Strafing Run",
  "Eagle Airstrike",
  "Eagle Cluster Bomb",
  "Eagle Napalam Aistrike",
  "Jump Pack",
  "Eagle Smoke Strike",
  "Eagle 110MM Rocket Pods",
  "Eagle 500KG Bomb",
  "M-102 Fast Recon Vehicle",
  "Orbital Precision Strike",
  "Orbital Gas Strike",
  "Orbital EMS Strike",
  "Orbital Smoke Strike",
  "HMG Emplacement",
  "Shield Generator Relay",
  "Tesla Tower",
  "Anti-Personnel Minefield",
  "Supply Pack",
  "Grenade Launcher",
  "Laser Cannon",
  "Incendiary Mines",
  '"Guard Dog" Rover',
  "Ballistic Shield Backpack",
  "Arc Thrower",
  "Quasar Cannon",
  "Shield Generator Pack",
  "Machine Gun Sentry",
  "Gatling Sentry",
  "Mortar Sentry",
  '"Guard Dog"',
  "Autocannon Sentry",
  "Rocket Sentry",
  "EMS Mortar Sentry",
  "Patriot Exosuit",
  "Emancipator Exosuit",
  "MLS-4X Commando",
  "Anti-Tank Mines",
  "Orbital Napalm Barrage",
  "Sterilizer",
  '"Guard Dog" Dog Breath',
  "SH-51 Directional Shield",
  "E/AT-12 Anti-Tank Emplacement",
  "A/FLAM-40 Flame Sentry",
];

// #Primaries
const primaries = [
  "AR-23 Liberator",
  "AR-23P Liberator Penetrator",
  "AR-23C Liberator Concussive",
  "StA-52 Assault Rifle",
  "AR-23A Liberator Carbine",
  "AR-61 Tenderizer",
  "BR-14 Adjudicator",
  "R-2124 Constitution",
  "R-63 Diligence",
  "R-63CS Diligence Counter Sniper",
  "PLAS-39 Accelerator Rifle",
  "MP-98 Knight",
  "StA-11 SMG",
  "SMG-32 Reprimand",
  "SMG-37 Defender",
  "SMG-72 Pummeler",
  "SG-8 Punisher",
  "SG-8S Slugger",
  "SG-20 Halt",
  "SG-451 Cookout",
  "SG-225 Breaker",
  "SG-225SP Breaker Spray&Pray",
  "SG-225IE Breaker Incendiary",
  "CB-9 Exploding Crossbow",
  "R-36 Eruptor",
  "SG-8P Punisher Plasma",
  "ARC-12 Blitzer",
  "LAS-5 Scythe",
  "LAS-16 Sickle",
  "PLAS-1 Scorcher",
  "PLAS-101 Purifier",
  "Flam-66 Torcher",
  "JAR-5 Dominator",
];

// #Secondaries
const secondaries = [
  "P-2 Peacemaker",
  "P-19 Redeemer",
  "P-113 Verdict",
  "P-4 Senator",
  "CQC-19 Stun Lance",
  "CQC-30 Stun Baton",
  "P-11 Stim Pistol",
  "SG-22 Bushwhacker",
  "P-72 Crisper",
  "GP-31 Grenade Pistol",
  "LAS-7 Dagger",
  "Plas-15 Loyalist",
];

// #Grenades
const grenades = [
  "G-6 Frag",
  "G-12 High Explosive",
  "G-10 Incendiary",
  "G-16 Impact",
  "G-13 Incendiary Impact",
  "G-23 Stun",
  "G-4 Gas",
  "G-3 Smoke",
  "G-123 Thermite Grenade",
  "K-2 Throwing Knife",
];

// #Armor/Helmets
const armor_sets = [
  {
    helmet: "B-01 Tactical 1",
    armor: "B-01 Tactical 1",
    cape: "Drape of Glory",
    banner: "Drape of Glory",
  },
  {
    helmet: "B-01 Tactical 2",
    armor: "B-01 Tactical 2",
    cape: "Drape of Glory",
    banner: "Drape of Glory",
  },
  {
    helmet: "B-01 Tactical 3",
    armor: "B-01 Tactical 3",
    cape: "Drape of Glory",
    banner: "Drape of Glory",
  },
  {
    helmet: "B-01 Tactical 4",
    armor: "B-01 Tactical 4",
    cape: "Drape of Glory",
    banner: "Drape of Glory",
  },
  {
    helmet: "B-08 Light Gunner",
    armor: "B-08 Light Gunner",
    cape: "Foesmasher",
    banner: "Foesmasher",
  },
  {
    helmet: "SC-34 Infiltrator",
    armor: "SC-34 Infiltrator",
    cape: "Independence Bringer",
    banner: "Independence Bringer",
  },
  {
    helmet: "FS-05 Marksman",
    armor: "FS-05 Marksman",
    cape: "Liberty's Herald",
    banner: "Liberty's Herald",
  },
  {
    helmet: "FS-11 Executioner",
    armor: "FS-11 Executioner",
    cape: "Foesmasher",
    banner: "Foesmasher",
  },
  {
    helmet: "CE-35 Trench Engineer",
    armor: "CE-35 Trench Engineer",
    cape: "Tideturner",
    banner: "Tideturner",
  },
  {
    helmet: "CM-09 Bonesnapper",
    armor: "CM-09 Bonesnapper",
    cape: "Stars and Suffrage",
    banner: "Stars and Suffrage",
  },
  {
    helmet: "DP-40 Hero of the Federation",
    armor: "DP-40 Hero of the Federation",
    cape: "Unblemished Allegiance",
    banner: "Unblemished Allegiance",
  },
  {
    helmet: "FS-23 Battle Master",
    armor: "FS-23 Battle Master",
    cape: "Judgment Day",
    banner: "Judgment Day",
  },
  {
    helmet: "FS-61 Dreadnought",
    armor: "FS-61 Dreadnought",
    cape: "Liberty's Herald",
    banner: "Liberty's Herald",
  },
  {
    helmet: "SC-30 Trailblazer Scout",
    armor: "SC-30 Trailblazer Scout",
    cape: "Cresting Honor",
    banner: "Cresting Honor",
  },
  {
    helmet: "SA-04 Combat Technician",
    armor: "SA-04 Combat Technician",
    cape: "Mantle of True Citizenship",
    banner: "Mantle of True Citizenship",
  },
  {
    helmet: "CM-14 Physician",
    armor: "CM-14 Physician",
    cape: "Blazing Samaritan",
    banner: "Blazing Samaritan",
  },
  {
    helmet: "DP-11 Champion of the People",
    armor: "DP-11 Champion of the People",
    cape: "Light of Eternal Liberty",
    banner: "Light of Eternal Liberty",
  },
  {
    helmet: "SA-25 Steel Trooper",
    armor: "SA-25 Steel Trooper",
    cape: "Tyrant Hunter",
    banner: "Tyrant Hunter",
  },
  {
    helmet: "SA-12 Servo-Assisted",
    armor: "SA-12 Servo-Assisted",
    cape: "Posterity's Gratitude",
    banner: "Posterity's Gratitude",
  },
  {
    helmet: "SA-32 Dynamo",
    armor: "SA-32 Dynamo",
    cape: "Bastion of Integrity",
    banner: "Bastion of Integrity",
  },
  {
    helmet: "EX-03 Prototype 3",
    armor: "EX-03 Prototype 3",
    cape: "Botslayer",
    banner: "Botslayer",
  },
  {
    helmet: "EX-16 Prototype 16",
    armor: "EX-16 Prototype 16",
    cape: "Martyris Rex",
    banner: "Martyris Rex",
  },
  {
    helmet: "EX-00 Prototype X",
    armor: "EX-00 Prototype X",
    cape: "Agent of Oblivion",
    banner: "Agent of Oblivion",
  },
  {
    helmet: "CE-27 Ground Breaker",
    armor: "CE-27 Ground Breaker",
    cape: "Harbinger of True Quality",
    banner: "Harbinger of True Quality",
  },
  {
    helmet: "CE-07 Demolition Specialist",
    armor: "CE-07 Demolition Specialist",
    cape: "Eagle's Fury",
    banner: "Eagle's Fury",
  },
  {
    helmet: "FS-55 Devastator",
    armor: "FS-55 Devastator",
    cape: "Freedom's Tapestry",
    banner: "Freedom's Tapestry",
  },
  {
    helmet: "CW-36 Winter Warrior",
    armor: "CW-36 Winter Warrior",
    cape: "Dissident's Nightmare",
    banner: "Dissident's Nightmare",
  },
  {
    helmet: "CW-22 Kodiak",
    armor: "CW-22 Kodiak",
    cape: "Pinions of Everlasting Glory",
    banner: "Pinions of Everlasting Glory",
  },
  {
    helmet: "CW-4 Arctic Ranger",
    armor: "CW-4 Arctic Ranger",
    cape: "Order of the Venerated Ballot",
    banner: "Order of the Venerated Ballot",
  },
  {
    helmet: "B-27 Fortified Commando",
    armor: "B-27 Fortified Commando",
    cape: null,
    banner: null,
  },
  {
    helmet: "PH-9 Predator",
    armor: "PH-9 Predator",
    cape: "Mark of the Crimson Fang",
    banner: "Mark of the Crimson Fang",
  },
  {
    helmet: "PH-202 Twigsnapper",
    armor: "PH-202 Twigsnapper",
    cape: "Executioner's Canopy",
    banner: "Executioner's Canopy",
  },
  {
    helmet: "TR-40 Gold Eagle",
    armor: "TR-40 Gold Eagle",
    cape: "Foesmasher",
    banner: "Foesmasher",
  },
  {
    helmet: "I-09 Heatseeker",
    armor: "I-09 Heatseeker",
    cape: "Purifying Eclipse",
    banner: "Purifying Eclipse",
  },
  {
    helmet: "I-102 Draconaught",
    armor: "I-102 Draconaught",
    cape: "The Breach",
    banner: "The Breach",
  },
  {
    helmet: "CE-101 Guerilla Gorilla",
    armor: "CE-101 Guerilla Gorilla",
    cape: null,
    banner: null,
  },
  {
    helmet: "SC-37 Legionnaire",
    armor: "SC-37 Legionnaire",
    cape: null,
    banner: null,
  },
  {
    helmet: "AF-50 Noxious Ranger",
    armor: "AF-50 Noxious Ranger",
    cape: "Standard of Safe Distance",
    banner: "Standard of Safe Distance",
  },
  {
    helmet: "AF-02 Haz-Master",
    armor: "AF-02 Haz-Master",
    cape: "Patient Zero's Rememberance",
    banner: "Patient Zero's Rememberance",
  },
  {
    helmet: "DP-00 Tactical",
    armor: "DP-00 Tactical",
    cape: null,
    banner: null,
  },
  {
    helmet: "UF-50 Bloodhound",
    armor: "UF-50 Bloodhound",
    cape: "Pride of the Whistleblower",
    banner: "Pride of the Whistleblower",
  },
  {
    helmet: "UF-16 Inspector",
    armor: "UF-16 Inspector",
    cape: "Proof of Faultless Virtue",
    banner: "Proof of Faultless Virtue",
  },
  {
    helmet: "PH-56 Jaguar",
    armor: "PH-56 Jaguar",
    cape: null,
    banner: null,
  },
];

const data = { stratagems, primaries, secondaries, grenades, armor_sets };
export default data;
